---
name: 'ci'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  hadolint:
    name: 'hadolint'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './hadolint'
        with:
          args: '*/Dockerfile'

  yamllint:
    name: 'yamllint'
    runs-on: 'self-hosted'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './yamllint'
