---
name: 'ci'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  yamllint:
    name: 'yamllint'
    runs-on: self-hosted
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './yamllint'
