---
name: 'ci'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  Yamllint:
    name: 'Yamllint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './yamllint'
